#Manually running a workflow--trigger Pipeline
on:
  workflow_dispatch:       #2 space

permissions:
  id-token: write
  contents: read 
 
 
jobs:
  job1:
    name: azure login
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: hyperskill/azure-login@v3.0.0
        with:
          client-id: "ef918e69-be10-4267-9ac6-87000e61deb6"          #${{ secrets.AZURE_CLIENT_ID }}
          client_secret: "38A8Q~U~aTmk33LX5b0KdO8NaGRS0Y_fWKG.3bqo"
          tenant-id: "36df4507-8aab-483e-88d3-d7982c300017"           #${{ secrets.AZURE_TENANT_ID }}
          subscription-id: "bc401604-b6cc-41b5-8eb3-22ccca3b29ff"      #${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
                     
  job2:
    needs: job1
    name: terraform install
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"
        
  job3:
    needs: job2
    name: terraform command
    runs-on: ubuntu-latest
    steps:
      - name: Terraform init
        run: terraform init


      - name:  fmt
        run: terraform fmt

      - name: validate
        run: terraform validate


      - name:  plan
        run: terraform plan

      - name: apply
        run: terraform apply -auto-approve

